# fly.toml app configuration file generated for mafia-party-game on 2026-02-28T01:13:49-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maf1a'
primary_region = 'sjc'

[build]

[env]
  DATABASE_PATH = '/data/mafia.db'
  PORT = '3000'

[[mounts]]
  source = 'mafia_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
